services:
  - type: web
    name: student-portal
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn ssp.wsgi:application --bind 0.0.0.0:$PORT --timeout 120"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: student-portal-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: *.onrender.com,student-portal-1-zyif.onrender.com
    healthCheckPath: /
    autoDeploy: true

  - type: pserv
    name: student-portal-db
    env: docker
    plan: free
    image: postgres:15-alpine
    envVars:
      - key: POSTGRES_DB
        value: student_portal
      - key: POSTGRES_USER
        generateValue: true
      - key: POSTGRES_PASSWORD
        generateValue: true
