# Generated by Django 5.1.6 on 2025-02-26 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'verbose_name': 'notes', 'verbose_name_plural': 'notes'},
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='decription',
            new_name='description',
        ),
    ]
